global:
  scrape_interval: 15s # 默认抓取间隔
  evaluation_interval: 15s # 规则评估间隔

# 告警管理配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# 规则文件配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
default_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# 自定义抓取配置
scrape_configs:
  # 监控 Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 监控 API 服务
  - job_name: 'ios-club-api'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          app: 'ios-club-api'
          environment: 'development'
