// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iOSClub.Data;

#nullable disable

namespace iOSClub.Data.Migrations
{
    [DbContext(typeof(ClubContext))]
    [Migration("20260905131228_AddArticleDepartmentVisibility")]
    partial class AddArticleDepartmentVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_search");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iOSClub.Data.DataObjects.ArticleDO", b =>
                {
                    b.Property<string>("Path")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ArticleOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VisibleToDepartment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Path");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Path")
                        .HasDatabaseName("articles_search_idx")
                        .HasAnnotation("ParadeDB:IndexFieldAliases", new[] { "", "", "" })
                        .HasAnnotation("ParadeDB:IndexFieldKinds", new[] { "property", "property", "property" })
                        .HasAnnotation("ParadeDB:IndexFieldOpclasses", new[] { "", "", "" })
                        .HasAnnotation("ParadeDB:IndexFieldProperties", new[] { "Path", "Title", "Content" })
                        .HasAnnotation("ParadeDB:IndexFieldTokenizers", new[] { "", "pdb.jieba", "pdb.jieba" })
                        .HasAnnotation("ParadeDB:IndexKeyProperty", "Path")
                        .HasAnnotation("ParadeDB:IndexSearchTokenizer", "jieba");

                    b.HasIndex("VisibleToDepartment");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.CategoryDO", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.ClientApplicationDO", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HomepageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeedEMail")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RedirectUris")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("SupportsPkce")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId");

                    b.ToTable("ClientApplications");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.DepartmentDO", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Name");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.ResourceDO", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.StaffDO", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentName");

                    b.HasIndex("Identity");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.StudentDO", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Academy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EMail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("PoliticalLandscape")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Academy");

                    b.HasIndex("ClassName");

                    b.HasIndex("JoinTime");

                    b.HasIndex("PhoneNum");

                    b.HasIndex("PoliticalLandscape");

                    b.HasIndex("UserId")
                        .HasDatabaseName("students_search_idx")
                        .HasAnnotation("ParadeDB:IndexFieldAliases", new[] { "", "", "", "" })
                        .HasAnnotation("ParadeDB:IndexFieldKinds", new[] { "property", "property", "property", "property" })
                        .HasAnnotation("ParadeDB:IndexFieldOpclasses", new[] { "", "", "", "" })
                        .HasAnnotation("ParadeDB:IndexFieldProperties", new[] { "UserId", "UserName", "ClassName", "Academy" })
                        .HasAnnotation("ParadeDB:IndexFieldTokenizers", new[] { "", "pdb.jieba", "pdb.jieba", "pdb.jieba" })
                        .HasAnnotation("ParadeDB:IndexKeyProperty", "UserId")
                        .HasAnnotation("ParadeDB:IndexSearchTokenizer", "jieba");

                    b.HasIndex("UserName");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.ArticleDO", b =>
                {
                    b.HasOne("iOSClub.Data.DataObjects.CategoryDO", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("iOSClub.Data.DataObjects.DepartmentDO", null)
                        .WithMany()
                        .HasForeignKey("VisibleToDepartment")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.StaffDO", b =>
                {
                    b.HasOne("iOSClub.Data.DataObjects.DepartmentDO", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentName");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.CategoryDO", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("iOSClub.Data.DataObjects.DepartmentDO", b =>
                {
                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
